//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo4SQLMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int Masp { get; set; }
        public string Tensp { get; set; }
        public string Note { get; set; }
        public Nullable<double> Gia { get; set; }
        public string Anh { get; set; }
        public Nullable<double> Sale { get; set; }
        public Nullable<int> Soluong { get; set; }
    }
}
