//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo4SQLMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int MANV { get; set; }
        public string TENNV { get; set; }
        public string GIOITINH { get; set; }
        public Nullable<int> SDT { get; set; }
        public string DIACHI { get; set; }
    }
}
