//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo4SQLMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public string HANGSP { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string ANH { get; set; }
        public Nullable<double> GIASPB { get; set; }
    }
}
